### ISSUE TITLE
Utilites/SMRFT - Unable to download xLODGen.83.7z, Whole Process Halts

### ISSUE THREAD

**Issue by EP1CN3SS2** [wabbajack-tools/mod-lists#2787]
Really? One removed link puts a halt to the entire process? What kind of incompetency is this? I even downloaded the file from somewhere else, put it in the downloads folder and it still gives the same error/fails. Why even put a mega link into the modlist, who needs xLODGen, thats an advanced process that I could do myself if I wanted to. I wanted patches and a baseline for modding, LODs are not baseline, its extra.

**Comment by halgari** [comment]
Would you rather it install a broken modlist? The whole point of WJ is not to provide you with a baseline, it's to provide a perfectly modded install that requires no extra modifications. Lack of LODs would break that value proposition.

**Comment by halgari** [comment]
And you can always download the file by hand and put it in the downloads folder than continue the process. I'd rather have an app that works correctly every time, than one that randomly breaks stuff.
