### ISSUE TITLE
Mod list will not load

### ISSUE THREAD

**Issue by detharize** [wabbajack-tools/mod-lists#3002]
The Skyrim VR Essentials modlist fails to install after downloading most of the files.  Here are the errors it gives at the end of the wabbajack log file.

Also when trying to download the files for loverslab, I have to manually select the tempered skin mod.  It is split into 3 separate files but after selecting the first file to download, wabbajack leaves the loverslab site and continues with downloading whatever is in its list.  I think that is why I am getting the first error at 6131.91.

6131.81 - Found 814 total files, 779 matching filesize
6131.91 - Unable to download Tempered_Skins_for_Males_-_SOS_Light_Version_-_part_2_of_2_v2.051.7z (ManualDownloader+State|https://www.loverslab.com/files/file/3692-sos-light-version-with-tempered-skins-for-males-sse/)
6131.91 - Unable to download Skyrim_Realistic_Overhaul_Part_1.7z (ModDBDownloader+State|https://www.moddb.com/downloads/start/116891?referer=https%3A%2F%2Fwww.moddb.com%2Fmods%2Fskyrim-realistic-overhaul%2Fdownloads)
6131.91 - Unable to download Skyrim_Realistic_Overhaul_Part_3.7z (ModDBDownloader+State|https://www.moddb.com/downloads/start/116934?referer=https%3A%2F%2Fwww.moddb.com%2Fmods%2Fskyrim-realistic-overhaul%2Fdownloads)
6131.91 - Cannot continue, was unable to download one or more archives
6131.94 - File hash check (-42) 552e22e6f9075bd4e67b5f86cd0b85993deb47f1ba01fc4d0f94dbd7e9bf0a71
6132.06 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
6132.38 - File hash check (-42) 552e22e6f9075bd4e67b5f86cd0b85993deb47f1ba01fc4d0f94dbd7e9bf0a71

**Comment by renanm99** [comment]
I was having the same problem minutes ago. These "Unable to download" erros is due to the download mirror missing, or Wabbajack just can't get it rght. There is the downloads folder that you selected and all the mods are been downloaded. You can just download it yourself and put the downloaded zip file there and Wabbajack won't have to download it but just check if it's there. Go to https://www.moddb.com/downloads/start/116891?referer=https%3A%2F%2Fwww.moddb.com%2Fmods%2Fskyrim-realistic-overhaul%2Fdownloads for example and download the zip file yourself and just put it under the UVRE download folder, then try running the installation again. Hope it helps! :)

**Comment by detharize** [comment]
Yeah thanks,  I just downloaded Auriel's Dream (Which I already had but deleted when I started downloading the UVRE) and ran into the same problem.  I discovered I could do what you said and it will finish loading.  Now I will go back and do the same with the UVRE.

**Comment by shaion01** [comment]
Greetings! I actually have the same problem and the file (link) is gone from nexusmods homepage too.

6131.91 - Unable to download Tempered_Skins_for_Males_-SOS_Light_Version-_part_2_of_2_v2.051.7z (ManualDownloader+State|https://www.loverslab.com/files/file/3692-sos-light-version-with-tempered-skins-for-males-sse/)

Could anyone e-mail me that file or is there anyway to modify the wabbajack list and remove both this and part_1_of_1? I really want to play, got all the other files downloaded :-/

![image](https://user-images.githubusercontent.com/105082628/167216469-d20605a9-d339-4583-ab95-e4357892f386.png)
