### ISSUE TITLE
Blockhead and misaligned UI

### ISSUE THREAD

**Issue by UESCMark4** [wabbajack-tools/mod-lists#3321]
I have an issuer where I get the "Install Blockhead" on the face in character creation menu.
I also have a misaligned UI.
I've tried installing fresh twice already and I can't figure out where it comes from.
![2023-05-03 213411](https://user-images.githubusercontent.com/130183452/236026371-3bad3b32-2b4a-48c6-9c31-5128f3992f6b.png)

**Comment by Althro** [comment]
Please report this on the appropriate lists github or in their support server.

**Comment by UESCMark4** [comment]
My bad. I didn't see I was on the overall Wabbajack-tools.
