### ISSUE TITLE
Corrupted Lexy's LOTD mod list

### ISSUE THREAD

**Issue by Alariann** [wabbajack-tools/mod-lists#466]
Hi,
The current downloadable Lexy's mod list is corrupted. 
The error: "modlist is corrupt unexpected character encountered while parsing value: B"
The file inside is not JSON and must be wrongly encoded I think. The zipped modlist file is attached here.
[modlist.zip](https://github.com/wabbajack-tools/mod-lists/files/4565221/modlist.zip)

**Comment by halgari** [comment]
Read the release notes for Wabbajack 2.0.
